version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
